### ISSUE TITLE
Clarify status of Contributors

### ISSUE THREAD

**Issue by clehner** [ssbc/ssbc-org#1]
> ### Contributors
> 
> Anyone is welcome to contribute to the Consortium through pull requests, design insights, comms, or discussion. People who have contributed a lot to the Consortium over a period of time can be invited to become a Member.

I read this as implying that anyone who contributes is a contributer. However, the [Team page](https://github.com/orgs/ssbc/teams) distinguishes between Contributors and Members within the organization.

I think the document should be revised to clarify the process for a non-member becoming a Contributor and for a Contributor becoming a Member.

**Comment by mixmix** [comment]
I think it could be anyone who contributes is a contributor. In practice it seems like it's a little bit closer than some one off interactions. e.g. contributors can make branches on origin (as opposed to having to always work on a fork). .. what else? 
I think contributors can attend meetings, and can help inform decision making.

Can you clarify what further needs clarity?

**Comment by pfraze** [comment]
@clehner I think youre right that it reads like it's automatic, but it's not (and I dont think it should be). It needs to be at our discretion; after youve made notable contributions, youre in

We also need to ground this in the business discussion
